# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/mt6768-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter penangf fogorow,$(TARGET_DEVICE)),)

endif
